project:
  type: "website"


website:
  title: "GeoJupyter"
  site-url: "https://geojupyter.org"

  repo-url: &repo-url "https://github.com/geojupyter/geojupyter.org"
  repo-actions: ["edit", "issue"]

  # HACK: Quarto previews don't show drafts as expected. This will cause drafts
  # to be rendered in production as well! But that's probably fine.
  # (https://github.com/quarto-dev/quarto-cli/issues/10279)
  draft-mode: "unlinked"

  navbar:
    logo: "https://avatars.githubusercontent.com/u/170677547?s=400&u=03648f729acc1a0f82ed15246feb7a77c1fcced7&v=4"

    left:
      - "about.md"
      - "projects.md"
      - "blog/index.md"
      - "interviews/index.md"
    right:
      - text: "{{< iconify simple-icons:zulip title='Zulip chat' label='Zulip chat' >}}"
        aria-label: "Zulip chat"
        href: "https://jupyter.zulipchat.com/#narrow/channel/471314-geojupyter"
      - icon: "github"
        aria-label: "GitHub"
        href: "https://github.com/geojupyter"

  page-footer:
    left: |
      © 2025 GeoJupyter Contributors.

      GeoJupyter is a community effort that includes many Jupyter contributors and follows all Jupyter guidelines, but is currently not an official Jupyter subproject.
    right: "Built with [Quarto](https://quarto.org/) ❤️"


format:
  html:
    theme: "spacelab"
    css: "styles.css"
    toc: true
    # Turn on emoji shortcodes (NOTE: Doesn't work in sidebar, nav or
    # front-matter):
    from: "markdown+emoji"
