project:
  type: "website"


website:
  title: "GeoJupyter"
  site-url: "https://geojupyter.github.io"

  repo-url: &repo-url "https://github.com/geojupyter/geojupyter.github.io"
  repo-actions: ["edit", "issue"]

  # HACK: Quarto previews don't show drafts as expected. This will cause drafts
  # to be rendered in production as well! But that's probably fine.
  # (https://github.com/quarto-dev/quarto-cli/issues/10279)
  draft-mode: "unlinked"

  navbar:
    left:
      - "about.md"
      - "blog/index.md"
    right:
      - icon: "github"
        aria-label: "GitHub"
        href: "https://github.com/geojupyter"

  page-footer:
    left: "© UC Berkeley 2024"
    right: "Built with [Quarto](https://quarto.org/) ❤️"


format:
  html:
    theme: "spacelab"
    css: "styles.css"
    toc: true
    # Turn on emoji shortcodes (NOTE: Doesn't work in sidebar, nav or
    # front-matter):
    from: "markdown+emoji"
