[project]
authors = ["Matt Fisher <mfisher87@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "geojupyter.github.io"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
render = "quarto render"
preview = "quarto preview"

[dependencies]
quarto = ">=1.5.57"
