name: "Initialize meeting notes"

on:
  workflow_dispatch:
    inputs:
      kind:
        type: "choice"
        description: "What kind of meeting?"
        options:
          - "core"
          - "hackathon"
      date:
        description: |
          Date of the meeting in `date --date` format, e.g.:
          "today", "tomorrow", "next wednesday", "2025-02-05", etc.
          See <https://www.gnu.org/software/coreutils/manual/html_node/Date-input-formats.html>
        required: false
        default: "today"
        type: "string"

  pull_request:  # TODO: Switch to issue comment?
    types:
      - "labeled"

# IMPORTANT: Enable 'Allow GitHub Actions to create and approve pull requests'
# in repo and organization Actions Settings.
permissions:
  contents: "write"
  pull-requests: "write"

jobs:
  create:
    if: "github.event_name != 'pull_request'"
    uses: "Quansight-Labs/hackmd-meeting-notes-action/.github/workflows/create-meeting-notes-pr.yml@main"
    with:
      date: "${{ inputs.date }}"
      template_path: ".github/meeting-notes-templates/{{ inputs.kind }}.md"
      output_path: "{{ inputs.kind }}/%Y-%m-%d.md"
      hackmd_team: "geojupyter"
      force_push: true
      pr_body: |
        Meeting notes initialized at ${env.hackmd_doc_url}.

        After the meeting, sync the notes from HackMD to this PR by adding the `sync-meeting-notes` label.
    secrets:
      HACKMD_TOKEN: "${{ secrets.HACKMD_TOKEN }}"

  sync:
    if: "github.event.label.name == 'sync-meeting-notes'"
    uses: "Quansight-Labs/hackmd-meeting-notes-action/.github/workflows/sync-meeting-notes-pr.yml@main"
    with:
      pr_number: "${{ github.event.number }}"
    secrets:
      HACKMD_TOKEN: "${{ secrets.HACKMD_TOKEN }}"
